<?xml version="1.0"?>
<!-- RRR Planer Manipulator XY plane-->
<robot name="rrr" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> 
  <xacro:property name="width" value="0.1" /> 
  <xacro:property name="width1" value="0.2" /> 
  <xacro:property name="height1" value="0.1" /> 
  <xacro:property name="height2" value="1.1" /> 
  <xacro:property name="height3" value="1.1" /> 
  <xacro:property name="height4" value="1.05" /> 

  <xacro:property name="axel_offset" value="0.05" /> 


  <xacro:include filename="$(find rangeaero_assignment)/rrr_description/urdf/rrr.gazebo" />
  <xacro:include filename="$(find rangeaero_assignment)/rrr_description/urdf/materials.xacro" />


  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

 
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width1} ${width1} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width1} ${width1} ${height1}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width1*width1 + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width1*width1)}" iyz="0.0"
	  izz="${mass / 12.0 * (width1*width1 + width1*width1)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <limit effort="10000" lower="-2.967" upper="2.967" velocity="0.5"/>
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link2">
    <collision>
      <origin xyz="0.5 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1.15 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.5 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1.15 0.1 0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0.5 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (0.1*0.1 + 0.1*0.1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (0.1*0.1 + 1.15*1.15)}" iyz="0.0"
	  izz="${mass / 12.0 * (0.1*0.1 + 1.15*1.15)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <limit effort="10000" lower="-2.967" upper="2.967" velocity="0.5"/>
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="1 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>



  <link name="link3">
    <collision>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="1.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="1.1 0.1 0.1"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (0.1*0.1 + 0.1*0.1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (0.1*0.1 + 0.1*0.1)}" iyz="0.0"
	  izz="${mass / 12.0 * (0.1*0.1 + 1.1*1.1)}"/>
    </inertial>
  </link>


  <joint name="joint3" type="revolute">
    <limit effort="10000" lower="-2.967" upper="2.967" velocity="0.5"/>
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="1 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>




  <link name="link4">
    <collision>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="1.05 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="1.05 0.1 0.1"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <origin xyz="0.5 0 0.05" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (0.1*0.1 + 0.1*0.1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (1.05*1.05 + 0.1*0.1)}" iyz="0.0"
	  izz="${mass / 12.0 * (1.05*1.05 + 0.1*0.1)}"/>
    </inertial>
  </link>



  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
